version: '3.4'

services:
  productdb:
    container_name: productdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
       - mongo_data:/data/db

  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
     - productdb
    ports:
      - "8000:80"
  
  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #depends_on:
    # - catalogdb
    ports:
      - "8001:80"   