version: '3.4'

services:
  productdb:
    image: mongo

  orderdb:
        image: mcr.microsoft.com/mssql/server:2017-latest

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Presentation/Product/GMicroservices.Product.WebApi/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Ordering/GMicroservices.Ordering.WebApi/Dockerfile

volumes:
  mongo_data: