version: '3.4'

services:
  productdb:
    container_name: productdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
       - mongo_data:/data/db

  parceldb:
    container_name: parceldb
    restart: always
    ports:
      - "6379:6379"

  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "murad628"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1401:1433"

  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
     - productdb
    ports:
      - "8000:80"
  
  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=ms;Password=murad628"
    depends_on:
     - orderdb
    ports:
      - "8001:80"   

  parcel.api:
    container_name: parcel.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
     - parceldb
    ports:
      - "8002:80"