version: '3.4'

services:
  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #depends_on:
    # - catalogdb
    ports:
      - "8000:80"
  
  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #depends_on:
    # - catalogdb
    ports:
      - "8001:80"   