version: '3.4'

services:
  productdb:
    container_name: productdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
       - mongo_data:/data/db

  parceldb:
    container_name: parceldb
    restart: always
    ports:
      - "6379:6379"

  orderdb:
    container_name: orderdb
    environment:
        SA_PASSWORD: "murad628"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1401:1433"

  userdb:
    container_name: userdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=UserDB
    restart: always
    ports:
      - "5432:5432"
    volumes:
       - postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  product.api:
    container_name: product.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
     - productdb
    ports:
      - "8000:80"
  
  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=ms;Password=murad628"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
     - orderdb
    ports:
      - "8001:80"   

  user.api:
    container_name: user.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=userdb;Port=5432;Database=UserDB;User Id=admin;Password=admin1234"
    depends_on:
     - userdb
    ports:
      - "8007:80"


  user.grpc:
    container_name: user.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=userdb;Port=5432;Database=UserDB;User Id=admin;Password=admin1234"
    depends_on:
     - userdb
    ports:
      - "8008:80"

  parcel.api:
    container_name: parcel.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
     - parceldb
    ports:
      - "8002:80"

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:ProductUrl=http://product.api"
      - "ApiSettings:ParcelUrl=http://parcel.api"
      - "ApiSettings:OrderingUrl=http://ordering.api"
      - "ApiSettings:UserUrl=http://user.api"
    depends_on:
      - product.api
      - parcel.api
      - ordering.api
      - user.api
    ports:
      - "8005:80"

  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - product.api
        - parcel.api
        - ordering.api
        - user.api
    ports:
      - "8010:80"