version: '3.4'

services:
  productdb:
    image: mongo

  parceldb:
     image: redis:alpine

  userdb:
     image: postgres

  orderdb:
        image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
     image: rabbitmq:3-management-alpine

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Presentation/Product/GMicroservices.Product.WebApi/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Presentation/Ordering/GMicroservices.Ordering.WebApi/Dockerfile
      
  parcel.api:
    image: ${DOCKER_REGISTRY-}parcelapi
    build:
        context: .
        dockerfile: Presentation/Parcel/GMicroservices.Parcel.WebApi/Dockerfile

  user.api:
     image: ${DOCKER_REGISTRY-}userapi
     build:
        context: .
        dockerfile: Presentation/User/GMicroservices.User.WebApi/Dockerfile

  user.grpc:
     image: ${DOCKER_REGISTRY-}usergrpc
     build:
       context: .
       dockerfile: Presentation/User/GMicroservices.User.Grpc/Dockerfile

  shopping.aggregator:
    image: ${DOCKER_REGISTRY-}shoppingaggregator
    build:
      context: .
      dockerfile: ApiGateways/Shoping.Aggregator/Dockerfile

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateways/OcelotApiGw/Dockerfile

volumes:
  mongo_data:
  postgres_data: