version: '3.4'

services:
  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Presentation/Product/GMicroservices.Product.WebApi/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Ordering/GMicroservices.Ordering.WebApi/Dockerfile
