version: '3.4'

services:
  productdb:
    image: mongo

  parceldb:
        image: redis:alpine

  orderdb:
        image: mcr.microsoft.com/mssql/server:2017-latest

  rabbitmq:
     image: rabbitmq:3-management-alpine

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Presentation/Product/GMicroservices.Product.WebApi/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Ordering/GMicroservices.Ordering.WebApi/Dockerfile

  parcel.api:
        image: ${DOCKER_REGISTRY-}parcelapi
        build:
          context: .
          dockerfile: Presentation/Parcel/GMicroservices.Parcel.WebApi/Dockerfile

volumes:
  mongo_data: